package com.example.project.security;

public enum Permission {
    DOCUMENT_VIEW,
    DOCUMENT_CREATE,
    DOCUMENT_UPDATE,
    DOCUMENT_DELETE,

    READER_VIEW,
    READER_CREATE,
    READER_UPDATE,
    READER_DELETE,

    LIBRARIAN_VIEW,
    LIBRARIAN_CREATE,
    LIBRARIAN_UPDATE,
    LIBRARIAN_DELETE,

    SUPPLIER_VIEW,
    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,

    GRN_VIEW,
    GRN_CREATE,
    GRN_UPDATE,
    GRN_DELETE,

    BORROW_SLIP_VIEW,
    BORROW_SLIP_CREATE,
    BORROW_SLIP_UPDATE,
    BORROW_SLIP_DELETE
}