package com.example.project.security;

public enum Permission {
    DOCUMENT_VIEW,
    DOCUMENT_CREATE,
    DOCUMENT_UPDATE,
    DOCUMENT_DELETE,

    READER_VIEW,
    READER_CREATE,
    READER_UPDATE,
    READER_DELETE,

    LIBRARIAN_VIEW,
    LIBRARIAN_CREATE,
    LIBRARIAN_UPDATE,
    LIBRARIAN_DELETE
}